### ISSUE TITLE
--

### ISSUE THREAD

**Issue by abdlmutii** [fowlerro/react-discord-components#1]
--

**Comment by fowlerro** [comment]
I chose React because I am mainly working with it, and at the time I created this library, I needed that in my other project written in React, right now I don't have time to continue working on it unfortunately, but maybe in the future, when I come back to maintaining it, maybe web components would be good idea to consider, it should probably be rewritten anyway, as it has a lot of problems

**Comment by abdlmutii** [comment]
> I chose React because I am mainly working with it, and at the time I created this library, I needed that in my other project written in React, right now I don't have time to continue working on it unfortunately, but maybe in the future, when I come back to maintaining it, maybe web components would be good idea to consider, it should probably be rewritten anyway, as it has a lot of problems

Cool bro. I felt like it will be better with html
